// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDHxKeWhPAVpm5ZXgD6UqP8aR3DRcQoh0',
    appId: '1:1037956874722:web:b3856f58f4c8f88874f9bb',
    messagingSenderId: '1037956874722',
    projectId: 'nrcs-8301e',
    authDomain: 'nrcs-8301e.firebaseapp.com',
    databaseURL: 'https://nrcs-8301e-default-rtdb.firebaseio.com',
    storageBucket: 'nrcs-8301e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDHxKeWhPAVpm5ZXgD6UqP8aR3DRcQoh0',
    appId: '1:1037956874722:android:your_android_app_id',
    messagingSenderId: '1037956874722',
    projectId: 'nrcs-8301e',
    databaseURL: 'https://nrcs-8301e-default-rtdb.firebaseio.com',
    storageBucket: 'nrcs-8301e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDHxKeWhPAVpm5ZXgD6UqP8aR3DRcQoh0',
    appId: '1:1037956874722:ios:your_ios_app_id',
    messagingSenderId: '1037956874722',
    projectId: 'nrcs-8301e',
    databaseURL: 'https://nrcs-8301e-default-rtdb.firebaseio.com',
    storageBucket: 'nrcs-8301e.firebasestorage.app',
  );
}
